-- ============================================================
-- SEED DATA: Sample devotionals and date ideas
-- Run after initial schema migration
-- ============================================================

-- Sample devotionals (7 days)
INSERT INTO public.devotionals (publish_date, title, scripture_reference, scripture_text, reflection, couple_action, category) VALUES
  (CURRENT_DATE, 'Love That Endures', '1 Corinthians 13:4-7', 'Love is patient, love is kind. It does not envy, it does not boast, it is not proud. It does not dishonor others, it is not self-seeking, it is not easily angered, it keeps no record of wrongs.', 'Reflect on what patience in love looks like in your relationship. Where have you seen patience flourish? Where might it need more attention?', 'Share one specific moment this week where your partner showed patience with you, and thank them for it.', 'love'),
  (CURRENT_DATE + 1, 'Building Trust Together', 'Proverbs 3:5-6', 'Trust in the Lord with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight.', 'Trust is the foundation of every strong relationship. Consider how trusting God together can deepen the trust you share with each other.', 'Pray together about one area of your relationship where you want to grow in trust.', 'trust'),
  (CURRENT_DATE + 2, 'The Power of Words', 'Proverbs 18:21', 'The tongue has the power of life and death, and those who love it will eat its fruit.', 'Our words have incredible power in our relationships. Think about the last week — how have your words brought life to your partner?', 'Write your partner a short note of encouragement and leave it where they will find it.', 'communication'),
  (CURRENT_DATE + 3, 'Growing in Grace', 'Ephesians 4:32', 'Be kind and compassionate to one another, forgiving each other, just as in Christ God forgave you.', 'Grace is not just for Sunday mornings — it is the daily currency of healthy relationships. Where do you need to extend more grace?', 'Think of one thing you have been holding onto. Choose to release it tonight and tell your partner you forgive them.', 'forgiveness'),
  (CURRENT_DATE + 4, 'Seeking First the Kingdom', 'Matthew 6:33', 'But seek first his kingdom and his righteousness, and all these things will be given to you as well.', 'When we make God the priority in our relationship, everything else falls into place. How can you seek His kingdom together?', 'Discuss one way you can make God more central in your daily routine as a couple.', 'faith'),
  (CURRENT_DATE + 5, 'Iron Sharpens Iron', 'Proverbs 27:17', 'As iron sharpens iron, so one person sharpens another.', 'Healthy relationships involve growth, and growth can sometimes be uncomfortable. How are you helping each other become better?', 'Ask your partner: What is one area where I can support your growth this month?', 'growth'),
  (CURRENT_DATE + 6, 'A Cord of Three Strands', 'Ecclesiastes 4:12', 'Though one may be overpowered, two can defend themselves. A cord of three strands is not quickly broken.', 'Your relationship is strongest when God is at the center. Together with Him, you can face anything.', 'Spend 10 minutes praying together tonight, thanking God for your relationship and asking for His continued guidance.', 'prayer');

-- Sample date ideas
INSERT INTO public.date_ideas (title, description, category, estimated_cost, estimated_duration, scripture_tie, is_challenge) VALUES
  ('Sunset Prayer Walk', 'Take a walk together at sunset and pray as you go. Share what you are grateful for and what you are trusting God with.', 'spiritual', 'free', '45 minutes', 'Psalm 19:1 — The heavens declare the glory of God', FALSE),
  ('Cook a New Recipe Together', 'Pick a recipe neither of you has tried. Work together in the kitchen and enjoy the results. No phones allowed!', 'at-home', '$', '90 minutes', NULL, FALSE),
  ('Letters of Encouragement', 'Each write a letter to the other listing 10 things you admire about them. Exchange and read aloud.', 'creative', 'free', '30 minutes', '1 Thessalonians 5:11 — Encourage one another and build each other up', FALSE),
  ('Volunteer Together', 'Find a local charity or church event and serve together. Serving side by side builds deep connection.', 'spiritual', 'free', '3 hours', 'Galatians 5:13 — Serve one another humbly in love', TRUE),
  ('Star Gazing', 'Find a spot away from city lights. Bring a blanket, some snacks, and marvel at creation together.', 'adventure', 'free', '60 minutes', 'Genesis 15:5 — Look up at the sky and count the stars', FALSE),
  ('Coffee Shop Bible Study', 'Pick a book of the Bible and study it together at a local coffee shop. Take turns reading and discussing.', 'spiritual', '$', '90 minutes', NULL, FALSE),
  ('Photo Walk Challenge', 'Walk around your neighborhood and challenge each other to take the best photos. Compare results over dessert.', 'creative', 'free', '60 minutes', NULL, TRUE),
  ('Double Date Dinner', 'Invite another Christian couple to dinner. Share stories, play games, and build community together.', 'simple', '$$', '2 hours', 'Hebrews 10:24-25 — Spur one another on toward love and good deeds', FALSE),
  ('Memory Lane Drive', 'Drive to places that are meaningful in your relationship — where you met, first date spot, etc. Share memories at each stop.', 'adventure', '$', '2 hours', NULL, FALSE),
  ('Worship Night In', 'Create a playlist of your favorite worship songs. Light candles, worship together, and spend time in prayer.', 'at-home', 'free', '45 minutes', 'Psalm 100:2 — Worship the Lord with gladness', FALSE);
