// Preset avatars (C3a) — illustrated, cyclable avatars for users who don't
// upload a photo. Generated by DiceBear's "open-peeps" style (close to the
// Couple Joy look) on a soft brand-purple background. We store the resulting
// PNG URL in `profiles.avatar_url`, so the `Avatar` component renders it like
// any other image (no assets to bundle). Pure module — no native imports — so
// it's safe to unit-test and import anywhere.

const DICEBEAR_STYLE = 'open-peeps';
const BACKGROUND = 'eee7ff'; // primary[100], soft purple

export const PRESET_AVATAR_SEEDS = [
  'Aria',
  'Bear',
  'Clover',
  'Dewdrop',
  'Ember',
  'Fox',
  'Honey',
  'Ivy',
  'Juniper',
  'Luna',
  'Pippin',
  'Wren',
] as const;

export function presetAvatarUrl(seed: string): string {
  return `https://api.dicebear.com/9.x/${DICEBEAR_STYLE}/png?seed=${encodeURIComponent(
    seed
  )}&backgroundColor=${BACKGROUND}`;
}

export const PRESET_AVATAR_URLS: string[] = PRESET_AVATAR_SEEDS.map(presetAvatarUrl);

// True when a stored avatar_url is a DiceBear preset (vs an uploaded R2 photo).
export function isPresetAvatar(url: string | null | undefined): boolean {
  return !!url && url.includes('api.dicebear.com');
}
