-- 00019 — date library seed: ~340 ideas (350 total with the original 10).
-- Owner approved schema + factors 2026-07-05 (category, cost, location,
-- accessibility, season, stage fit). Owner runs this in Studio.
-- accessibility_tags vocabulary: mobility-friendly · low-energy · no-car-needed
-- location_type: home | outdoor | in_town | travel   season: any|spring|summer|fall|winter

INSERT INTO public.date_ideas
  (title, description, category, estimated_cost, estimated_duration, location_type, accessibility_tags, season, stage_fit)
VALUES
-- ═══ ADVENTURE (49) ═══
('Sunrise Summit Hike', 'Pick a hill or lookout, pack coffee, and watch the day begin together.', 'adventure', 'free', '3-4 hours', 'outdoor', '{}', 'any', '{dating,engaged,married}'),
('Kayak or Canoe Rental', 'Two paddles, one rhythm. Learn to steer together — literally.', 'adventure', '$$', '2-3 hours', 'outdoor', '{}', 'summer', '{dating,engaged,married}'),
('Bike Ride to Somewhere New', 'Ride to a neighborhood or park neither of you has explored.', 'adventure', 'free', '2-3 hours', 'outdoor', '{no-car-needed}', 'any', '{dating,engaged,married}'),
('Indoor Rock Climbing', 'Belay for each other — trust with a literal rope attached.', 'adventure', '$$', '2 hours', 'in_town', '{}', 'any', '{dating,engaged,married}'),
('Geocaching Afternoon', 'Download a geocaching app and hunt hidden treasures near you.', 'adventure', 'free', '2-3 hours', 'outdoor', '{no-car-needed}', 'any', '{dating,engaged,married}'),
('First-Bus Adventure', 'Board the first bus that arrives and get off somewhere interesting.', 'adventure', '$', 'half day', 'in_town', '{no-car-needed,mobility-friendly}', 'any', '{dating,engaged}'),
('Sunset Chasing Drive', 'Find the best sunset viewpoint within an hour of home.', 'adventure', '$', '2-3 hours', 'outdoor', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Farmers Field U-Pick', 'Pick berries, apples, or pumpkins depending on the season.', 'adventure', '$', '2 hours', 'outdoor', '{}', 'fall', '{dating,engaged,married}'),
('Night Walk with Flashlights', 'Your usual walking route becomes brand new after dark.', 'adventure', 'free', '1 hour', 'outdoor', '{mobility-friendly,no-car-needed}', 'any', '{dating,engaged,married}'),
('Tourist in Your Own City', 'Do everything a visitor would do: landmarks, photos, overpriced fudge.', 'adventure', '$$', 'full day', 'in_town', '{mobility-friendly}', 'any', '{dating,engaged,married}'),
('Waterfall Field Trip', 'Find the nearest waterfall and make the trip a mini pilgrimage.', 'adventure', '$', 'half day', 'outdoor', '{}', 'spring', '{dating,engaged,married}'),
('Tandem Bike Wobble', 'Rent a tandem bike and laugh through the learning curve.', 'adventure', '$$', '1-2 hours', 'outdoor', '{}', 'summer', '{dating,engaged}'),
('Horseback Trail Ride', 'A guided ride — no experience needed, awe included.', 'adventure', '$$$', '2-3 hours', 'outdoor', '{}', 'any', '{dating,engaged,married}'),
('Hot Air Balloon Watch', 'Find a balloon festival or launch site and watch the sky fill.', 'adventure', 'free', '2 hours', 'outdoor', '{mobility-friendly,low-energy}', 'summer', '{dating,engaged,married}'),
('Tide Pools & Creation Talk', 'Explore a shoreline at low tide and marvel at the small things God made.', 'adventure', 'free', '2 hours', 'outdoor', '{}', 'summer', '{dating,engaged,married}'),
('Snow Day Fort Build', 'Build a snow fort like you are both nine years old again.', 'adventure', 'free', '2 hours', 'outdoor', '{}', 'winter', '{dating,engaged,married}'),
('Ice Skating Hand-in-Hand', 'Skate, wobble, hold on to each other. That is the point.', 'adventure', '$', '2 hours', 'in_town', '{}', 'winter', '{dating,engaged,married}'),
('Sledding Hill Race', 'Two sleds, one hill, best of five. Loser makes cocoa.', 'adventure', 'free', '2 hours', 'outdoor', '{}', 'winter', '{dating,engaged,married}'),
('Open-Water Swim or Beach Day', 'Salt, sun, and zero agenda. Bring a psalm to read at sunset.', 'adventure', 'free', 'half day', 'outdoor', '{low-energy}', 'summer', '{dating,engaged,married}'),
('Climb a Fire Tower', 'Find a lookout tower and earn the view together.', 'adventure', 'free', 'half day', 'outdoor', '{}', 'any', '{dating,engaged}'),
('Zipline Course', 'Scream together. Bond instantly.', 'adventure', '$$$', '2-3 hours', 'outdoor', '{}', 'summer', '{dating,engaged}'),
('Roller Rink Throwback', 'Retro skating, cheesy music, holding hands on the slow lap.', 'adventure', '$', '2 hours', 'in_town', '{}', 'any', '{dating,engaged,married}'),
('Kite Flying Rematch', 'Two kites and a windy field. Yes, it counts as a sport.', 'adventure', '$', '1-2 hours', 'outdoor', '{mobility-friendly}', 'spring', '{dating,engaged,married}'),
('Batting Cages Face-Off', 'Take turns, keep score, trash-talk lovingly.', 'adventure', '$', '1 hour', 'in_town', '{}', 'any', '{dating,engaged,married}'),
('Mini Golf Championship', 'Eighteen tiny holes of highly competitive love.', 'adventure', '$', '1-2 hours', 'in_town', '{mobility-friendly}', 'any', '{dating,engaged,married}'),
('Go-Kart Grand Prix', 'Race twice: once for fun, once for pride.', 'adventure', '$$', '1-2 hours', 'in_town', '{}', 'any', '{dating,engaged}'),
('Bowling & Milkshakes', 'Classic lanes, silly team names, shakes after.', 'adventure', '$$', '2 hours', 'in_town', '{mobility-friendly}', 'any', '{dating,engaged,married}'),
('Escape Room Duo', 'Sixty minutes, one locked room, your combined brainpower.', 'adventure', '$$', '1-2 hours', 'in_town', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Trampoline Park Hour', 'Jump until you both remember you are not teenagers.', 'adventure', '$$', '1 hour', 'in_town', '{}', 'any', '{dating,engaged}'),
('Archery Range Intro', 'Learn to shoot a bow. Cupid jokes strongly encouraged.', 'adventure', '$$', '1-2 hours', 'in_town', '{}', 'any', '{dating,engaged,married}'),
('Paddleboat Afternoon', 'Pedal a little boat around a pond like a rom-com scene.', 'adventure', '$', '1 hour', 'outdoor', '{low-energy}', 'summer', '{dating,engaged,married}'),
('Corn Maze Challenge', 'Get lost on purpose. Pray you find the exit before dark.', 'adventure', '$', '2 hours', 'outdoor', '{}', 'fall', '{dating,engaged,married}'),
('Drive-In Movie Night', 'Blankets, snacks, radio audio, old-school romance.', 'adventure', '$$', '3 hours', 'outdoor', '{mobility-friendly,low-energy}', 'summer', '{dating,engaged,married}'),
('Meteor Shower Stakeout', 'Check the astronomy calendar, drive somewhere dark, count wishes.', 'adventure', 'free', '2-3 hours', 'outdoor', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Botanical Garden Wander', 'Slow walk, big flowers, zero rush.', 'adventure', '$', '2 hours', 'outdoor', '{mobility-friendly,low-energy}', 'spring', '{dating,engaged,married}'),
('Storm Watching from the Car', 'Park somewhere safe with snacks and watch the sky perform.', 'adventure', 'free', '1-2 hours', 'outdoor', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('New Trail Tuesday', 'Pick a trail neither of you has hiked and just go.', 'adventure', 'free', 'half day', 'outdoor', '{}', 'any', '{dating,engaged,married}'),
('Fishing at Dawn', 'Lines in the water, quiet conversation, patience practice.', 'adventure', '$', 'half day', 'outdoor', '{low-energy}', 'summer', '{dating,engaged,married}'),
('Camp in the Backyard', 'Tent, s''mores, and the shortest commute in camping history.', 'adventure', '$', 'overnight', 'home', '{no-car-needed}', 'summer', '{dating,engaged,married}'),
('Full-Moon Walk', 'Time a walk to the full moon and leave your phones home.', 'adventure', 'free', '1 hour', 'outdoor', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Ferry Ride to Anywhere', 'If there is a ferry near you, ride it for the view alone.', 'adventure', '$', 'half day', 'travel', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Train Day Trip', 'Take a regional train one town over and explore on foot.', 'adventure', '$$', 'full day', 'travel', '{mobility-friendly,no-car-needed}', 'any', '{dating,engaged,married}'),
('One-Tank Road Trip', 'Drive as far as one tank allows, turn around at halfway.', 'adventure', '$$', 'full day', 'travel', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Overnight in a Cabin', 'One night away, no wifi, board games and a fireplace.', 'adventure', '$$$', 'overnight', 'travel', '{low-energy}', 'winter', '{engaged,married}'),
('Hot Springs Soak', 'Find natural springs or a spa day pass and just soak.', 'adventure', '$$$', 'half day', 'travel', '{mobility-friendly,low-energy}', 'winter', '{engaged,married}'),
('Bucket-List Landmark Visit', 'Pick the closest thing on your shared bucket list and finally go.', 'adventure', '$$$', 'full day', 'travel', '{}', 'any', '{dating,engaged,married}'),
('Sunflower or Tulip Field', 'Find a bloom field in season and walk the rows.', 'adventure', '$', '2 hours', 'outdoor', '{mobility-friendly,low-energy}', 'spring', '{dating,engaged,married}'),
('Lighthouse Hunt', 'Drive the coast (or lake shore) collecting lighthouses and photos.', 'adventure', '$', 'half day', 'travel', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Community Fun Run', 'Sign up for a local 5k and cross the line together.', 'adventure', '$$', 'half day', 'in_town', '{}', 'any', '{dating,engaged,married}'),
-- ═══ SPIRITUAL (49) ═══
('Psalm Walk at Sunrise', 'Walk at dawn taking turns reading one psalm aloud.', 'spiritual', 'free', '1 hour', 'outdoor', '{mobility-friendly,no-car-needed}', 'any', '{dating,engaged,married}'),
('Visit Another Congregation', 'Worship somewhere new together and compare notes over lunch.', 'spiritual', 'free', 'half day', 'in_town', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Communion at Home', 'Bread, juice, scripture, and unhurried gratitude at your own table.', 'spiritual', '$', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{engaged,married}'),
('Pray Over Your Home', 'Walk room to room praying for what happens in each one.', 'spiritual', 'free', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{engaged,married}'),
('Gratitude Jar Kickoff', 'Start a jar of daily thanks. Read them together at year end.', 'spiritual', '$', '30 minutes', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Memorize a Verse Together', 'Pick one verse, learn it by heart, quiz each other all week.', 'spiritual', 'free', '30 minutes', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Testimony Swap', 'Tell each other your full story with God — the long version.', 'spiritual', 'free', '2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged}'),
('Worship Playlist Exchange', 'Build each other a worship playlist and listen together.', 'spiritual', 'free', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Attend a Worship Night', 'Find a live worship event in town and go expectant.', 'spiritual', '$', '2-3 hours', 'in_town', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Fast a Meal, Pray Instead', 'Skip one meal together and spend the time in prayer.', 'spiritual', 'free', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{engaged,married}'),
('Read a Gospel in One Sitting', 'Mark reads aloud in about ninety minutes. Trade chapters.', 'spiritual', 'free', '2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Prayer List Date', 'Merge your prayer lists over coffee and pray through them.', 'spiritual', '$', '1 hour', 'in_town', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Write Your Vows to God', 'Separately write what you promise God for this relationship, then share.', 'spiritual', 'free', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{engaged,married}'),
('Church History Field Trip', 'Visit the oldest church building nearby and learn its story.', 'spiritual', 'free', '2 hours', 'in_town', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Creation Documentary Night', 'Watch a nature documentary as worship — wonder counts.', 'spiritual', 'free', '2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Blessing Box Build', 'Assemble a box of encouragement for someone God puts on your hearts.', 'spiritual', '$', '1-2 hours', 'home', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Sabbath Afternoon', 'Four hours, no screens, no errands. Rest as a discipline.', 'spiritual', 'free', 'half day', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Pray for Your Future', 'Take turns praying out loud for the marriage you are building.', 'spiritual', 'free', '30 minutes', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged}'),
('Hymn Sing from the Hymnal', 'Find old hymnals and sing the greats badly and joyfully.', 'spiritual', 'free', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Bible Character Deep Dive', 'Pick one figure — Ruth, David, Peter — and study their arc together.', 'spiritual', 'free', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Prayer Labyrinth or Garden', 'Find a prayer garden nearby and walk it slowly.', 'spiritual', 'free', '1-2 hours', 'outdoor', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Sermon & Sandwiches', 'Listen to one great sermon over lunch and discuss it after.', 'spiritual', '$', '2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Baptism Story Revisit', 'Visit or describe where each of you was baptized. Retell it all.', 'spiritual', 'free', '2 hours', 'in_town', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Pray the Examen Together', 'Review the week with the classic five-step Examen, out loud.', 'spiritual', 'free', '30 minutes', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{engaged,married}'),
('Scripture Lettering Night', 'Hand-letter a verse each for the other person to keep.', 'spiritual', '$', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Christian Concert Night', 'Buy tickets to a worship artist you both love.', 'spiritual', '$$$', '3-4 hours', 'in_town', '{mobility-friendly}', 'any', '{dating,engaged,married}'),
('Pray for Ten Neighbors', 'Walk your street praying quietly for each house you pass.', 'spiritual', 'free', '1 hour', 'outdoor', '{mobility-friendly,no-car-needed}', 'any', '{engaged,married}'),
('Faith Questions Jar', 'Write big faith questions on slips, draw and discuss one at a time.', 'spiritual', 'free', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Silent Retreat Hour', 'One hour, same room, total silence with God. Compare notes after.', 'spiritual', 'free', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{engaged,married}'),
('Bless Your Pastors', 'Write your church leaders a joint letter of encouragement.', 'spiritual', 'free', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Study the Fruit of the Spirit', 'One fruit per week for nine weeks — start tonight with love.', 'spiritual', 'free', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Proverbs Coffee Crawl', 'One proverb per coffee shop. Three shops, three conversations.', 'spiritual', '$$', 'half day', 'in_town', '{mobility-friendly}', 'any', '{dating,engaged,married}'),
('Kneel-Together Night', 'Literally kneel side by side before bed and pray unhurried.', 'spiritual', 'free', '30 minutes', 'home', '{no-car-needed,low-energy}', 'any', '{engaged,married}'),
('Song of Songs Reading', 'Read the Bible''s love poetry to each other. Yes, all of it.', 'spiritual', 'free', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{engaged,married}'),
('Map Your Spiritual Timeline', 'Draw timelines of your walks with God and overlay them.', 'spiritual', 'free', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged}'),
('Christian Bookstore Browse', 'Pick a book for each other and read the first chapter together.', 'spiritual', '$$', '2 hours', 'in_town', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Pray Through Photos', 'Scroll your camera roll and thank God for ten specific moments.', 'spiritual', 'free', '30 minutes', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Sunday Sunrise Service', 'Find an outdoor sunrise service — or hold your own with two chairs.', 'spiritual', 'free', '2 hours', 'outdoor', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Anoint Your Doorposts', 'Pray a blessing over every entrance to your home.', 'spiritual', '$', '30 minutes', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{married}'),
('Write a Psalm of Your Own', 'Co-write a psalm about your year — honest verses included.', 'spiritual', 'free', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Intercede for the World', 'Pick three global situations from the news and pray over a map.', 'spiritual', 'free', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Christian Podcast Walk', 'Queue one episode you both chose and walk while it plays.', 'spiritual', 'free', '1 hour', 'outdoor', '{mobility-friendly,no-car-needed}', 'any', '{dating,engaged,married}'),
('Retell Your God Stories', 'Each share three moments you clearly saw God move in your life.', 'spiritual', 'free', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Lectio Divina Evening', 'Read one short passage four slow times, sharing what stands out.', 'spiritual', 'free', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{engaged,married}'),
('Serve at Church Together', 'Sign up for the same serving team for one month.', 'spiritual', 'free', 'half day', 'in_town', '{mobility-friendly}', 'any', '{dating,engaged,married}'),
('Pray for Each Other''s Dreams', 'Name three dreams each, then trade lists and pray them back.', 'spiritual', 'free', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Candlelight Confession', 'Share one struggle each by candlelight, then pray grace over it.', 'spiritual', '$', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{engaged,married}'),
('Advent or Lent Kickoff', 'Begin the church season with a reading plan you choose together.', 'spiritual', 'free', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'winter', '{dating,engaged,married}'),
('Stargaze Psalm 19', 'Read "the heavens declare" under the actual heavens.', 'spiritual', 'free', '1 hour', 'outdoor', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
-- ═══ CREATIVE (48) ═══
('Paint Each Other''s Portrait', 'Cheap canvases, thirty minutes, zero talent required. Frame the results.', 'creative', '$', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Pottery Class Date', 'Take a wheel-throwing class and embrace the wonky mugs.', 'creative', '$$$', '2-3 hours', 'in_town', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Write Alternate Vows', 'Draft funny vows: "I promise to always share fries."', 'creative', 'free', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{engaged,married}'),
('Couple Photo Shoot DIY', 'Tripod, golden hour, ten poses. Print the best three.', 'creative', 'free', '2 hours', 'outdoor', '{mobility-friendly,no-car-needed}', 'any', '{dating,engaged,married}'),
('Build a Spotify Duet', 'Record yourselves singing one song. Keep it forever. Show no one.', 'creative', 'free', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Scrapbook Sprint', 'One hour, one glue stick, your last three months on paper.', 'creative', '$', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Home Video Documentary', 'Film a mock documentary about your ordinary Tuesday.', 'creative', 'free', '2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Lego or Puzzle Marathon', 'A thousand pieces and two stubborn optimists.', 'creative', '$$', '3-4 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'winter', '{dating,engaged,married}'),
('Paint-and-Sip at Home', 'Follow a YouTube painting tutorial with sparkling juice.', 'creative', '$', '2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Write a Children''s Story', 'Co-write the bedtime story you would read future kids.', 'creative', 'free', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{engaged,married}'),
('Candle Making Kit Night', 'Pour custom candles and name them after inside jokes.', 'creative', '$$', '2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Dance Lesson in the Kitchen', 'Learn one dance from a tutorial until you almost have it.', 'creative', 'free', '1 hour', 'home', '{no-car-needed}', 'any', '{dating,engaged,married}'),
('Thrift Store Outfit Swap', 'Ten dollars each: style a full outfit for the other. Wear it out.', 'creative', '$', '2-3 hours', 'in_town', '{mobility-friendly}', 'any', '{dating,engaged,married}'),
('Community Theater Night', 'See local actors give it everything for a tiny audience.', 'creative', '$$', '3 hours', 'in_town', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Open Mic Support Squad', 'Attend an open mic. Bonus points if one of you performs.', 'creative', '$', '2-3 hours', 'in_town', '{mobility-friendly,low-energy}', 'any', '{dating,engaged}'),
('Museum Sketch Date', 'Bring sketchbooks to a museum and draw your favorite pieces.', 'creative', '$', 'half day', 'in_town', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Make a Time Capsule', 'Fill a box with today: notes, prices, photos, predictions. Open in five years.', 'creative', '$', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Design Your Dream House', 'Sketch floor plans for the someday-house. Argue about closets.', 'creative', 'free', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Origami Together Hour', 'Fold cranes from a tutorial until one is recognizable.', 'creative', '$', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Photo Recreation Challenge', 'Recreate three old photos of yourselves, pose for pose.', 'creative', 'free', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{engaged,married}'),
('Karaoke Night Duet', 'One duet minimum. Commit to the bit.', 'creative', '$$', '2-3 hours', 'in_town', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Flower Arranging Face-Off', 'Grocery-store flowers, two vases, one impartial photo vote.', 'creative', '$', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'spring', '{dating,engaged,married}'),
('Handmade Card Exchange', 'Make each other a card for no occasion at all.', 'creative', '$', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Woodworking Mini Project', 'Build a birdhouse or shelf from a kit, together, with all fingers.', 'creative', '$$', 'half day', 'home', '{no-car-needed}', 'any', '{engaged,married}'),
('Bad Art Night', 'Intentionally create the worst masterpiece possible. Judge solemnly.', 'creative', '$', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Calligraphy Practice Date', 'Learn each other''s names in fancy lettering first.', 'creative', '$', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Write Letters to Year-Ten You', 'Letters to yourselves ten years married. Seal and store them.', 'creative', 'free', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{engaged,married}'),
('Tie-Dye Matching Shirts', 'Make deliberately loud matching shirts. Wear them in public once.', 'creative', '$', '2 hours', 'outdoor', '{mobility-friendly,low-energy}', 'summer', '{dating,engaged,married}'),
('Compose Your Song', 'Write one verse and a chorus about your story. Voice-memo it.', 'creative', 'free', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Stop-Motion Movie Night', 'Make a 30-second stop-motion film with household objects.', 'creative', 'free', '2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Puzzle Race: Two 300s', 'Two identical small puzzles, one timer. May the fastest win.', 'creative', '$', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Chalk the Driveway', 'Sidewalk chalk mural featuring your favorite verse.', 'creative', '$', '1 hour', 'outdoor', '{no-car-needed}', 'summer', '{dating,engaged,married}'),
('DIY Terrarium Build', 'Tiny glass gardens — one each, then swap custody monthly.', 'creative', '$$', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Cross-Stitch or Knit Along', 'Learn the same beginner pattern side by side.', 'creative', '$', '2-3 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'winter', '{dating,engaged,married}'),
('Interview Each Other on Video', 'Ten questions each, recorded. A gift to your future selves.', 'creative', 'free', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Vision Board Evening', 'Magazines, scissors, glue, and your next five years on poster board.', 'creative', '$', '2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Bookstore Blind Date', 'Buy each other a wrapped mystery book based on one hint.', 'creative', '$$', '2 hours', 'in_town', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Pressed Flower Frames', 'Collect, press, and frame flowers from a walk together.', 'creative', '$', '2 hours', 'outdoor', '{mobility-friendly,low-energy}', 'spring', '{dating,engaged,married}'),
('Learn Ukulele Basics', 'One cheap ukulele, two learners, three chords, endless laughing.', 'creative', '$$', '2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Paint Rocks, Hide Kindness', 'Paint verses on rocks and leave them around the neighborhood.', 'creative', '$', '2 hours', 'outdoor', '{mobility-friendly,no-car-needed}', 'summer', '{dating,engaged,married}'),
('Living Room Fashion Show', 'Model the weirdest combinations in your closets. Score cards required.', 'creative', 'free', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Blackout Poetry Night', 'Turn old newspaper pages into poems with a marker.', 'creative', 'free', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Gingerbread Build-Off', 'Two kits, one theme, zero structural integrity.', 'creative', '$$', '2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'winter', '{dating,engaged,married}'),
('Pumpkin Carving Duel', 'Carve on a theme and let the porch decide the winner.', 'creative', '$', '2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'fall', '{dating,engaged,married}'),
('Map Your Love Story', 'Draw a map marking everywhere significant to your story.', 'creative', '$', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Shadow Puppet Theater', 'A lamp, a sheet, and a retelling of David and Goliath.', 'creative', 'free', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Custom Mug Painting', 'Paint mugs at a ceramics studio — morning coffee upgrade.', 'creative', '$$', '2 hours', 'in_town', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Anniversary Logo Design', 'Design a crest or logo for your family. Debate the motto.', 'creative', 'free', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{engaged,married}')
;

INSERT INTO public.date_ideas
  (title, description, category, estimated_cost, estimated_duration, location_type, accessibility_tags, season, stage_fit)
VALUES
-- ═══ SIMPLE (49) ═══
('Front Porch Coffee', 'Two mugs, one porch, no phones until the cups are empty.', 'simple', 'free', '30 minutes', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Walk and Talk Loop', 'One neighborhood lap with one rule: no logistics talk.', 'simple', 'free', '1 hour', 'outdoor', '{mobility-friendly,no-car-needed}', 'any', '{dating,engaged,married}'),
('Question Deck Evening', 'Take turns with deep questions — phones in another room.', 'simple', 'free', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Watch the Sunset, That''s It', 'No agenda. Find west. Sit down. Hold hands.', 'simple', 'free', '1 hour', 'outdoor', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Library Date', 'Wander the stacks, pick books for each other, read side by side.', 'simple', 'free', '2 hours', 'in_town', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('People-Watch and Invent Stories', 'A bench, a busy spot, and whispered backstories for strangers.', 'simple', 'free', '1 hour', 'in_town', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Ice Cream Walk', 'One scoop each, longest possible route home.', 'simple', '$', '1 hour', 'in_town', '{mobility-friendly,no-car-needed}', 'summer', '{dating,engaged,married}'),
('Puddle-Jump Rain Walk', 'Rain gear on, dignity off. Hot drinks after.', 'simple', 'free', '1 hour', 'outdoor', '{no-car-needed}', 'spring', '{dating,engaged,married}'),
('Twenty-Photo Phone Tour', 'Show each other twenty old phone photos and the stories behind them.', 'simple', 'free', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Board Game Best-of-Five', 'One game you both know, played to the death (of pride).', 'simple', 'free', '2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Cloud Watching', 'A blanket, the sky, and competitive shape-spotting.', 'simple', 'free', '1 hour', 'outdoor', '{mobility-friendly,low-energy}', 'summer', '{dating,engaged,married}'),
('Bird Feeder Morning', 'Hang a feeder, make breakfast, keep a bird tally.', 'simple', '$', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{married}'),
('Swing Set Talk', 'Find playground swings at dusk and talk like teenagers.', 'simple', 'free', '1 hour', 'outdoor', '{no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('One-Song Slow Dance', 'One song in the kitchen every night this week. Start tonight.', 'simple', 'free', '15 minutes', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Garage Sale Treasure Hunt', 'Five dollars each. Weirdest find wins dessert.', 'simple', '$', '2 hours', 'in_town', '{mobility-friendly}', 'summer', '{dating,engaged,married}'),
('Newspaper and Pastries', 'A real paper, real pastries, and a slow Saturday hour.', 'simple', '$', '1 hour', 'in_town', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Compliment Battle', 'Trade genuine compliments until someone runs dry. Loser does dishes.', 'simple', 'free', '30 minutes', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Dog Park Visit (No Dog Needed)', 'Watch the dogs. Rank the dogs. Discuss future dog.', 'simple', 'free', '1 hour', 'outdoor', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Hammock Hour', 'One hammock, two people, geometry negotiations included.', 'simple', '$$', '1-2 hours', 'outdoor', '{low-energy}', 'summer', '{dating,engaged,married}'),
('First-Date Reenactment', 'Recreate your first date beat for beat, critique the remake.', 'simple', '$$', '2-3 hours', 'in_town', '{mobility-friendly}', 'any', '{engaged,married}'),
('Massage Trade Night', 'Ten minutes each of shoulder massage, then trade. Repeat.', 'simple', 'free', '30 minutes', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{engaged,married}'),
('Would-You-Rather Marathon', 'Fifty questions, escalating absurdity, snacks mandatory.', 'simple', 'free', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Blanket Fort Rebuild', 'Engineering review of your childhood fort skills. Movie inside.', 'simple', 'free', '2 hours', 'home', '{no-car-needed,low-energy}', 'winter', '{dating,engaged,married}'),
('Watch Old Home Videos', 'Trade childhood footage or photos and narrate them live.', 'simple', 'free', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Yes Afternoon', 'Three hours where the answer to every (reasonable) idea is yes.', 'simple', '$$', 'half day', 'in_town', '{mobility-friendly}', 'any', '{dating,engaged,married}'),
('Bucket List Sync', 'Write ten bucket items each, compare, and star the overlaps.', 'simple', 'free', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Thrift Book & Bench Read', 'Two dollar books, one park bench, quiet reading together.', 'simple', '$', '2 hours', 'outdoor', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Phone-Free Dinner', 'Phones in a drawer. Candles on. Conversation only.', 'simple', 'free', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Highs and Lows Walk', 'Share the week''s highest and lowest moments on a slow lap.', 'simple', 'free', '1 hour', 'outdoor', '{mobility-friendly,no-car-needed}', 'any', '{dating,engaged,married}'),
('Watch Planes Take Off', 'Park near the airport fence and pick destinations for each plane.', 'simple', 'free', '1-2 hours', 'outdoor', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Two-Dollar Store Gifts', 'Buy each other the best gift two dollars can find.', 'simple', '$', '1 hour', 'in_town', '{mobility-friendly}', 'any', '{dating,engaged,married}'),
('Neighborhood Christmas Lights', 'Drive or stroll the best-lit streets with cocoa in hand.', 'simple', 'free', '1-2 hours', 'outdoor', '{mobility-friendly,low-energy}', 'winter', '{dating,engaged,married}'),
('Morning Market Stroll', 'No list, no plan — just wander the market and share samples.', 'simple', '$', '2 hours', 'in_town', '{mobility-friendly}', 'any', '{dating,engaged,married}'),
('Team Crossword', 'One crossword, two brains, zero checking answers online.', 'simple', '$', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Feed the Ducks Properly', 'Buy actual duck-safe food and have a pond morning.', 'simple', '$', '1 hour', 'outdoor', '{mobility-friendly,low-energy}', 'spring', '{dating,engaged,married}'),
('Sticky-Note Love Bomb', 'Hide twenty notes around the house for each other to find all week.', 'simple', '$', '30 minutes', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Puzzle Piece a Day', 'Set up a table puzzle and do a little every evening together.', 'simple', '$', '30 minutes', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'winter', '{married}'),
('Car Wash Together', 'Buckets, music, and an inevitable water fight.', 'simple', '$', '1 hour', 'home', '{no-car-needed}', 'summer', '{dating,engaged,married}'),
('Sunrise Before Work', 'One alarm, one blanket, fifteen minutes of dawn before the day.', 'simple', 'free', '30 minutes', 'outdoor', '{mobility-friendly,low-energy}', 'any', '{engaged,married}'),
('Trivia Night Team', 'Join a pub-style trivia night as a two-person team.', 'simple', '$$', '2-3 hours', 'in_town', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Window Shop Downtown', 'Walk the main street pointing at things you would buy someday.', 'simple', 'free', '1-2 hours', 'in_town', '{mobility-friendly,no-car-needed}', 'any', '{dating,engaged,married}'),
('Love Language Check-In', 'Retake the love languages quiz and compare against last time.', 'simple', 'free', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Make Tomorrow Easier', 'Prep each other''s morning: lunches, clothes, coffee ready.', 'simple', 'free', '30 minutes', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{married}'),
('Old Playlist Time Machine', 'Play the songs from the year you met and tell the stories.', 'simple', 'free', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{engaged,married}'),
('Backyard Picnic', 'A blanket ten steps from your kitchen still counts as a picnic.', 'simple', '$', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'summer', '{dating,engaged,married}'),
('Text-Free Tech Swap', 'Trade phones for an hour (agreed rules) and show your worlds.', 'simple', 'free', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{engaged,married}'),
('Three Things Gratitude Swap', 'Trade three specific thank-yous about each other from this week.', 'simple', 'free', '15 minutes', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Watch a Storm from the Porch', 'Blankets, thunder, and nowhere else to be.', 'simple', 'free', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Plan Next Month''s Dates', 'Pick four ideas from this app and put them on the calendar.', 'simple', 'free', '30 minutes', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
-- ═══ AT-HOME (49) ═══
('Fancy Dinner, Home Edition', 'Dress up fully. Cloth napkins. Your own dining room, five stars.', 'at-home', '$$', '2-3 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Breakfast for Dinner', 'Pancake tower, bacon, pajamas at 7pm. No regrets.', 'at-home', '$', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Film Festival Night', 'Three short films or one trilogy — with intermission snacks.', 'at-home', '$', '3-4 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Cook-Off: One Ingredient', 'Same secret ingredient, two dishes, one dramatic tasting.', 'at-home', '$$', '2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Living Room Campout', 'Sleeping bags, lantern, whispered stories on the floor.', 'at-home', 'free', 'overnight', 'home', '{no-car-needed,low-energy}', 'winter', '{dating,engaged,married}'),
('Spa Night In', 'Face masks, foot soaks, cucumber water, robe dress code.', 'at-home', '$', '2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Video Game Co-op Night', 'Pick a two-player game and beat a level (or each other).', 'at-home', 'free', '2-3 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Bake Bread from Scratch', 'Knead, wait, and fill the whole house with that smell.', 'at-home', '$', 'half day', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Fondue Night', 'Cheese course, chocolate course, long forks, longer conversation.', 'at-home', '$$', '2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'winter', '{dating,engaged,married}'),
('Puzzle and Podcast', 'A jigsaw on the table and a series you only play together.', 'at-home', '$', '2-3 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Redecorate One Corner', 'Pick the saddest corner of your home and transform it together.', 'at-home', '$$', 'half day', 'home', '{no-car-needed}', 'any', '{married}'),
('Childhood Meal Swap', 'Cook each other the dinner you grew up on. Tell the stories.', 'at-home', '$', '2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Indoor Picnic on the Floor', 'Blanket on the living room floor, basket, ants not included.', 'at-home', '$', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'winter', '{dating,engaged,married}'),
('Documentary + Debrief', 'One documentary you both vote on, then a proper discussion after.', 'at-home', 'free', '2-3 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Bubble Bath and Playlist', 'Draw a bath, split a dessert, take turns picking songs.', 'at-home', '$', '1 hour', 'home', '{no-car-needed,low-energy}', 'any', '{married}'),
('Homemade Pizza Night', 'Dough from scratch, toppings bar, personal masterpiece each.', 'at-home', '$', '2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Board Game Tournament Bracket', 'Five games, running scoreboard, championship dessert.', 'at-home', 'free', '3-4 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'winter', '{dating,engaged,married}'),
('Cookbook Roulette', 'Random page, must cook whatever appears. May God help you.', 'at-home', '$$', '2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Home Karaoke Hour', 'YouTube lyric videos and full commitment. Neighbors were warned.', 'at-home', 'free', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Plant Night', 'Repot everything, name the plants, assign custody.', 'at-home', '$$', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'spring', '{dating,engaged,married}'),
('Massage + Worship Playlist', 'Slow evening: worship low, candles lit, take turns serving.', 'at-home', '$', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{married}'),
('Learn a Card Game Properly', 'Master one classic — cribbage, rummy, euchre — for life.', 'at-home', 'free', '2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Slideshow of Us', 'Build a photo slideshow of your best year and watch it big-screen.', 'at-home', 'free', '2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{engaged,married}'),
('Ice Cream Sundae Bar', 'Every topping the store had. Architectural ambition encouraged.', 'at-home', '$$', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'summer', '{dating,engaged,married}'),
('Try a New Cuisine at Home', 'Cook a cuisine neither of you has attempted. Order backup pizza.', 'at-home', '$$', '2-3 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Declutter and Donate Date', 'One closet, two boxes for charity, milkshakes after.', 'at-home', 'free', 'half day', 'home', '{no-car-needed}', 'any', '{married}'),
('Balcony Stargazing', 'Blankets and a stargazing app from wherever you can see sky.', 'at-home', 'free', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Write a Meal Plan Together', 'Plan next week''s dinners like co-chefs, not roommates.', 'at-home', 'free', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{married}'),
('Mocktail Mixology Lab', 'Invent three signature mocktails and name them after yourselves.', 'at-home', '$$', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Rearrange the Furniture', 'Move everything. Judge it. Maybe move it back. Team building.', 'at-home', 'free', '2 hours', 'home', '{no-car-needed}', 'any', '{married}'),
('Memory Lane Menu', 'Recreate the meal from a milestone night — first date, proposal.', 'at-home', '$$', '2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{engaged,married}'),
('Silent Reading Party', 'Two books, one couch, snacks, comfortable silence.', 'at-home', 'free', '2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Waffle Sunday', 'A slow waffle morning with every topping combination tested.', 'at-home', '$', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Home Workout Challenge', 'One workout video, two sore people, shared smoothie reward.', 'at-home', 'free', '1 hour', 'home', '{no-car-needed}', 'any', '{dating,engaged,married}'),
('Fireplace & Questions Night', 'Real fire or candle army — either way, slow questions.', 'at-home', 'free', '2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'winter', '{dating,engaged,married}'),
('Themed Movie Marathon', 'Pick a theme (space, decades, one actor) and triple-feature it.', 'at-home', '$', 'half day', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'winter', '{dating,engaged,married}'),
('Make Your Own Trail Mix', 'Bulk bins, custom blends, official taste-off.', 'at-home', '$', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Sunrise Breakfast Date', 'Set the table the night before; eat as the sun comes up.', 'at-home', '$', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{engaged,married}'),
('Two-Person Book Club', 'Same book, two weeks, snacks-and-verdict meeting tonight.', 'at-home', '$', '2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('DIY Photo Booth', 'Bedsheet backdrop, phone timer, props from the junk drawer.', 'at-home', 'free', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Soup and Bread Sunday', 'One pot of soup, one loaf, one long afternoon.', 'at-home', '$', '2-3 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'fall', '{dating,engaged,married}'),
('Hot Chocolate Flight', 'Three cocoa variations, rated on presentation and soul.', 'at-home', '$', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'winter', '{dating,engaged,married}'),
('Learn Ten Phrases of a Language', 'Pick the language of your dream trip and learn date-night basics.', 'at-home', 'free', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('At-Home Escape Kit', 'Print a DIY escape-room kit and race the timer at your table.', 'at-home', '$', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Budget Date-Night Draft', 'Plan the next quarter''s fun budget like a tiny board meeting.', 'at-home', 'free', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{engaged,married}'),
('Chocolate Tasting Night', 'Five bars, blind taste test, extremely serious scorecards.', 'at-home', '$$', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Build a Shared Playlist Live', 'Alternate adding songs for an hour; this becomes your soundtrack.', 'at-home', 'free', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Family Recipe Phone-a-Friend', 'Call a parent or grandparent for a recipe and cook it tonight.', 'at-home', '$', '2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Pancake Art Sunday', 'Squeeze-bottle batter portraits. Eat your mistakes.', 'at-home', '$', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
-- ═══ SERVICE (48) ═══
('Serve a Meal at a Shelter', 'Book a shift at a local shelter and serve side by side.', 'service', 'free', 'half day', 'in_town', '{mobility-friendly}', 'any', '{dating,engaged,married}'),
('Food Bank Packing Shift', 'Two hours sorting cans is a surprisingly great date.', 'service', 'free', '2-3 hours', 'in_town', '{mobility-friendly}', 'any', '{dating,engaged,married}'),
('Adopt a Grandparent Visit', 'Visit a senior home; bring cards, questions, and time.', 'service', 'free', '2 hours', 'in_town', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Neighborhood Cleanup Walk', 'Grabbers, bags, gloves, and the tidiest block in town.', 'service', '$', '2 hours', 'outdoor', '{no-car-needed}', 'any', '{dating,engaged,married}'),
('Make Blessing Bags', 'Assemble care kits (socks, snacks, notes) to keep in the car.', 'service', '$$', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Babysit for Young Parents', 'Gift a couple from church a free date night. Pay it forward.', 'service', 'free', 'half day', 'in_town', '{mobility-friendly,low-energy}', 'any', '{engaged,married}'),
('Yard Work for a Neighbor', 'Mow, rake, or shovel for someone who cannot. Then lemonade.', 'service', 'free', '2-3 hours', 'outdoor', '{no-car-needed}', 'any', '{dating,engaged,married}'),
('Bake and Deliver', 'Double a cookie batch and deliver half to someone lonely.', 'service', '$', '2-3 hours', 'home', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Write Cards to the Sick', 'A stack of get-well cards for a hospital ministry or hospice.', 'service', '$', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Animal Shelter Dog Walk', 'Give shelter dogs their happiest hour this week.', 'service', 'free', '2 hours', 'in_town', '{}', 'any', '{dating,engaged,married}'),
('Habitat Build Day', 'Swing hammers together on a Habitat for Humanity build.', 'service', 'free', 'full day', 'in_town', '{}', 'any', '{engaged,married}'),
('Sponsor-a-Child Letters', 'Write to (or choose) a sponsored child together.', 'service', '$$$', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Community Garden Shift', 'Weed and water a shared plot; take home something green.', 'service', 'free', '2 hours', 'outdoor', '{}', 'summer', '{dating,engaged,married}'),
('Church Nursery Team-Up', 'Serve a nursery shift together. Consider it cardio.', 'service', 'free', 'half day', 'in_town', '{mobility-friendly}', 'any', '{engaged,married}'),
('Meal Train Sign-Up', 'Cook for a family in a hard season and deliver it warm.', 'service', '$$', '2-3 hours', 'home', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Blood Donation Duo', 'Donate together, then juice and cookies like champions.', 'service', 'free', '2 hours', 'in_town', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Clothing Drive Sort', 'Purge closets, launder, fold, and deliver to a charity.', 'service', 'free', 'half day', 'home', '{mobility-friendly,no-car-needed}', 'any', '{engaged,married}'),
('Encourage a Missionary', 'Video call or care package for a missionary your church supports.', 'service', '$$', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Trail Maintenance Day', 'Join a park volunteer day: gloves on, trails restored.', 'service', 'free', 'half day', 'outdoor', '{}', 'any', '{dating,engaged}'),
('Free Lemonade Stand', 'Set up a genuinely free stand and bless passersby.', 'service', '$', '2-3 hours', 'outdoor', '{mobility-friendly}', 'summer', '{dating,engaged,married}'),
('Tutor or Mentor Together', 'Volunteer one evening at a youth or literacy program.', 'service', 'free', '2-3 hours', 'in_town', '{mobility-friendly,low-energy}', 'any', '{engaged,married}'),
('Nursing Home Hymn Sing', 'Bring song sheets and lead a sing-along hour.', 'service', 'free', '2 hours', 'in_town', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Grocery Surprise', 'Buy groceries for the person behind you or a family you know.', 'service', '$$', '1 hour', 'in_town', '{mobility-friendly}', 'any', '{dating,engaged,married}'),
('Church Workday Duo', 'Show up to the building workday as the two-person power team.', 'service', 'free', 'half day', 'in_town', '{}', 'any', '{dating,engaged,married}'),
('Foster Closet Volunteering', 'Sort donations for foster families for an afternoon.', 'service', 'free', '2-3 hours', 'in_town', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Thank the Night Shift', 'Deliver coffee and a note to a fire station or ER desk.', 'service', '$$', '1 hour', 'in_town', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Park Bench Blessing Kit', 'Chalk verses and tape snack bags to a park bench with a note.', 'service', '$', '1-2 hours', 'outdoor', '{mobility-friendly,no-car-needed}', 'summer', '{dating,engaged,married}'),
('Refugee Welcome Box', 'Assemble a household starter kit with a resettlement agency.', 'service', '$$$', '2-3 hours', 'in_town', '{mobility-friendly,low-energy}', 'any', '{engaged,married}'),
('Letters to Soldiers', 'Write encouragement letters through a troop-support charity.', 'service', '$', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Crisis Pregnancy Center Drive', 'Collect diapers and wipes, deliver with a prayer.', 'service', '$$', '2 hours', 'in_town', '{mobility-friendly,low-energy}', 'any', '{engaged,married}'),
('Operation Christmas Boxes', 'Pack shoebox gifts and pray over each recipient.', 'service', '$$', '2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'fall', '{dating,engaged,married}'),
('Widow/Widower Check-In', 'Visit someone recently bereaved with a meal and unhurried time.', 'service', '$', '2 hours', 'in_town', '{mobility-friendly,low-energy}', 'any', '{married}'),
('Bike Repair Giveaway', 'Fix up old bikes and donate them to kids who need wheels.', 'service', '$', 'half day', 'home', '{no-car-needed}', 'any', '{dating,engaged}'),
('Serve Your Server Day', 'Eat somewhere cheap, tip extravagantly, write a kind note.', 'service', '$$', '1-2 hours', 'in_town', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Church Tech Booth Shift', 'Learn and run slides or sound for a service, together.', 'service', 'free', 'half day', 'in_town', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Prayer Booth at a Market', 'Offer "free prayer" at a community event — brave and beautiful.', 'service', 'free', '2-3 hours', 'in_town', '{mobility-friendly,low-energy}', 'summer', '{married}'),
('Litter Plog Jog', 'Jog (or walk) with a trash bag — fitness plus service.', 'service', 'free', '1 hour', 'outdoor', '{no-car-needed}', 'any', '{dating,engaged,married}'),
('School Supply Drive', 'Fill backpacks for kids before the school year starts.', 'service', '$$', '2 hours', 'in_town', '{mobility-friendly,low-energy}', 'summer', '{dating,engaged,married}'),
('Snow Angel Patrol', 'Shovel three driveways anonymously before breakfast.', 'service', 'free', '2 hours', 'outdoor', '{}', 'winter', '{dating,engaged,married}'),
('Fence or Paint Fix-Up', 'Help repaint or repair for an elderly homeowner.', 'service', '$', 'half day', 'outdoor', '{}', 'summer', '{engaged,married}'),
('Care Package for a Student', 'Mail a finals-week box to a college kid from church.', 'service', '$$', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Community Fridge Stock-Up', 'Fill a neighborhood fridge or pantry box to the brim.', 'service', '$$', '1 hour', 'in_town', '{mobility-friendly}', 'any', '{dating,engaged,married}'),
('Hospital Waiting Room Kits', 'Drop off activity kits for families in long waits.', 'service', '$$', '2 hours', 'in_town', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Single Parent Car Care', 'Sponsor or perform an oil change and car wash for a single parent.', 'service', '$$', '2 hours', 'in_town', '{}', 'any', '{married}'),
('VBS Volunteer Week', 'Sign up for vacation Bible school crew together next summer.', 'service', 'free', 'full day', 'in_town', '{mobility-friendly}', 'summer', '{engaged,married}'),
('Coats in the Car', 'Keep gloves and coats in your trunk all winter to give away.', 'service', '$$', '1 hour', 'in_town', '{mobility-friendly,low-energy}', 'winter', '{dating,engaged,married}'),
('Neighbor Dinner Invite', 'Invite the neighbor you barely know to dinner this week.', 'service', '$$', '2-3 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{married}'),
('Thank-You Blitz', 'Write ten thank-you notes to people who shaped you both. Mail them.', 'service', '$', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
-- ═══ FOOD (48) ═══
('Taco Crawl', 'Three taco spots, one verdict. Science demands sacrifice.', 'food', '$$', '2-3 hours', 'in_town', '{mobility-friendly}', 'any', '{dating,engaged,married}'),
('Hole-in-the-Wall Roulette', 'Eat at the tiny place you always pass and never enter.', 'food', '$$', '1-2 hours', 'in_town', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Sushi Making Attempt', 'Rolling mats, sticky rice, and structurally questionable rolls.', 'food', '$$', '2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Farmers Market Chopped', 'Buy five mystery ingredients; invent dinner from only those.', 'food', '$$', 'half day', 'in_town', '{mobility-friendly}', 'summer', '{dating,engaged,married}'),
('Dessert-First Dinner', 'Order dessert first, entree second. Rules are fake anyway.', 'food', '$$', '2 hours', 'in_town', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Food Truck Friday', 'Find the truck cluster and split everything.', 'food', '$$', '2 hours', 'in_town', '{mobility-friendly}', 'summer', '{dating,engaged,married}'),
('Homemade Pasta Night', 'Flour clouds, hand-cranked noodles, sauce from an old recipe.', 'food', '$', '2-3 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Breakfast Diner Hop', 'One diner for coffee, another for pancakes, ranked mercilessly.', 'food', '$$', '2-3 hours', 'in_town', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('International Grocery Tour', 'Explore an international market and buy five new-to-you items.', 'food', '$', '2 hours', 'in_town', '{mobility-friendly}', 'any', '{dating,engaged,married}'),
('Bake Your Wedding Cake (Trial)', 'Attempt the cake you had (or want). Compare to the professionals.', 'food', '$$', 'half day', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{engaged,married}'),
('Ramen Night Out', 'Slurp loudly at the best ramen counter in reach.', 'food', '$$', '1-2 hours', 'in_town', '{mobility-friendly,low-energy}', 'winter', '{dating,engaged,married}'),
('Five-Course at Home', 'Tiny portions, five courses, printed menu with pretentious names.', 'food', '$$', '3 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{engaged,married}'),
('Farm-to-Table Splurge', 'Save up for the nice place and order the tasting menu.', 'food', '$$$', '3 hours', 'in_town', '{mobility-friendly,low-energy}', 'any', '{engaged,married}'),
('Doughnut Shop Crawl', 'The definitive neighborhood doughnut ranking, established today.', 'food', '$', '2 hours', 'in_town', '{mobility-friendly}', 'any', '{dating,engaged,married}'),
('Cook Through One Country', 'Pick a country and make a full menu from it tonight.', 'food', '$$', '3 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Blindfold Taste Test', 'Ten mystery spoonfuls each. Trust exercises, but delicious.', 'food', '$', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Bubble Tea Flight', 'Try three flavors you have never ordered. Rank the pearls.', 'food', '$', '1-2 hours', 'in_town', '{mobility-friendly,low-energy}', 'any', '{dating,engaged}'),
('Grill Masters Evening', 'Fire up the grill and cook everything — even the dessert.', 'food', '$$', '2-3 hours', 'home', '{mobility-friendly,no-car-needed}', 'summer', '{dating,engaged,married}'),
('Pie from Absolute Scratch', 'Crust included. Butter is a love language.', 'food', '$', 'half day', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'fall', '{dating,engaged,married}'),
('Brunch Like Tourists', 'Book the brunch spot with the line. Order the famous thing.', 'food', '$$', '2 hours', 'in_town', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Copycat Restaurant Dish', 'Reverse-engineer your favorite restaurant order at home.', 'food', '$$', '2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Hot Sauce Gauntlet', 'Mild to regrettable, with milk on standby.', 'food', '$', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged}'),
('Cheese Board Architecture', 'Build an unreasonable cheese board and eat it as dinner.', 'food', '$$', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Seasonal Fruit Feast', 'Whatever is peak-season, buy too much and eat it outside.', 'food', '$', '1-2 hours', 'outdoor', '{mobility-friendly,low-energy}', 'summer', '{dating,engaged,married}'),
('Bake Bread for the Block', 'Bake four loaves; keep one, give three away warm.', 'food', '$', 'half day', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{married}'),
('Ice Cream Homemade', 'No machine needed — bag-shake ice cream and topping chaos.', 'food', '$', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'summer', '{dating,engaged,married}'),
('Curry Night School', 'Learn one proper curry from a video by someone''s grandmother.', 'food', '$$', '2-3 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Diner at Midnight', 'Late-night diner booth, bottomless coffee, big questions.', 'food', '$', '2 hours', 'in_town', '{mobility-friendly,low-energy}', 'any', '{dating,engaged}'),
('Picnic Charcuterie in the Park', 'Assemble the fancy snack spread, carry it to a view.', 'food', '$$', '2-3 hours', 'outdoor', '{mobility-friendly,low-energy}', 'spring', '{dating,engaged,married}'),
('Soup Dumpling Quest', 'Find the best soup dumplings in reach. Burn tongues joyfully.', 'food', '$$', '2 hours', 'in_town', '{mobility-friendly,low-energy}', 'winter', '{dating,engaged,married}'),
('Recreate Your First Meal', 'Whatever you ate the day you met, eat it again tonight.', 'food', '$$', '2 hours', 'in_town', '{mobility-friendly,low-energy}', 'any', '{engaged,married}'),
('Bakery Sampler Morning', 'One of everything small at the best local bakery.', 'food', '$$', '1-2 hours', 'in_town', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('DIY Burger Lab', 'Invent signature burgers and name them after each other.', 'food', '$$', '2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Smoothie Bar Morning', 'Blend three inventions each; the winner becomes "our smoothie."', 'food', '$', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'summer', '{dating,engaged,married}'),
('Apple Orchard + Pie After', 'Pick apples in the morning, bake the pie that afternoon.', 'food', '$$', 'full day', 'outdoor', '{}', 'fall', '{dating,engaged,married}'),
('Street Food Bucket List', 'List five street foods to try this year; start with one today.', 'food', '$', '2 hours', 'in_town', '{mobility-friendly}', 'any', '{dating,engaged,married}'),
('Fancy Coffee Education', 'Pour-over versus press versus espresso — taste and take sides.', 'food', '$$', '1-2 hours', 'in_town', '{mobility-friendly,low-energy}', 'any', '{dating,engaged,married}'),
('Cast Iron Skillet Cookie', 'One giant cookie, two spoons, straight from the oven.', 'food', '$', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Hometown Dish Exchange', 'Each cook the dish your hometown is known for. Judge diplomatically.', 'food', '$$', '2-3 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Seafood Boil Newspaper Table', 'Newspaper tablecloth, big pot, no utensils allowed.', 'food', '$$$', '2-3 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'summer', '{engaged,married}'),
('Chocolate Fondue for Two', 'Melt chocolate; dip everything that stands still.', 'food', '$', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'winter', '{dating,engaged,married}'),
('Slow Cooker Sunday', 'Start it after church; smell it all afternoon; feast at six.', 'food', '$', 'full day', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'fall', '{married}'),
('Corn on the Cob Festival', 'Grill a dozen ears with three butter variations. Summer rules.', 'food', '$', '1-2 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'summer', '{dating,engaged,married}'),
('Milkshake Mixology', 'Invent milkshake flavors from whatever the freezer offers.', 'food', '$', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Tea Ceremony Slow Hour', 'Brew loose-leaf properly and sip it slower than feels normal.', 'food', '$', '1 hour', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Progressive Dinner by Foot', 'Appetizer, entree, and dessert at three walkable places.', 'food', '$$$', '3 hours', 'in_town', '{mobility-friendly,no-car-needed}', 'any', '{dating,engaged,married}'),
('Bake-Off: Secret Recipes', 'Each bake your best thing without revealing it beforehand.', 'food', '$', '2-3 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}'),
('Season Finale Feast', 'Cook a feast themed to the show you just finished together.', 'food', '$$', '2-3 hours', 'home', '{mobility-friendly,no-car-needed,low-energy}', 'any', '{dating,engaged,married}')
;
